language: php

php:
  - "5.6"
  - "7.0"

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test;" -u root; fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-text --configuration phpunit_$DB.xml --coverage-clover=./build/logs/clover.xml
  - php vendor/bin/phpcs -n --report=full

after_success:
  - travis_retry composer require satooshi/php-coveralls ~0.6
  - php vendor/bin/coveralls -v